# Generated by Django 2.2.2 on 2019-06-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190618_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='surname',
        ),
    ]
